### PR TITLE
Add support for the chromium browser.

### PR DESCRIPTION
**Pull request by gusennan**
Adds support for the chromium driver, which is the fully open-source variant of Chrome.

### CODE REVIEW

**Comment by gusennan** [comment]
(P.S. this is Nate G. from work)

**Review by dougnoel — APPROVED** [review]
I'm good with this as long as it passes the tests and code coverage is above 80%

**Comment by tyBouch** [comment]
Looks like we just need to re-run the build, and then update the branch with master.

**Comment by gusennan** [comment]
I pulled from master.  I was wondering if it's also necessary to install chromium in the continuous integration VM? The error message in the test seemed to indicate it couldn't find chromium. If so, could someone point me to where I would do that?

**Comment by gusennan** [comment]
closing in favor of https://github.com/dougnoel/sentinel/pull/416

**Pull request closed without merging**
